#!/usr/bin/ksh
(( $# == 0 )) && { print "usage: mkperl filename"; exit 1; }
filename=$1

if [ -f "$filename" ]; then
   print -n "$filename exists, over write (y/n)? "
   read ans 
   [ $ans = "n" -o $ans = "N" ] && exit 0
fi

a=$(echo "$filename" | grep "\.pl$")
if [ -z "$a" ]; then
   filename="$filename".pl
fi

> $filename

d=$(date "+%m/%d/%y")
finger 2>/dev/null 1>&2 # to see if finger exists or not 
if (( $? != 0 )); then
   your_name=${MYNAME:-" put your name here"}
else
   your_name=$(finger $(whoami)|grep -i "in real life"|cut -d: -f3)
fi

shbang=$(which perl)
[ -n "$shbang" ] && shbang=$shbang" -w" || shbang="/usr/bin/perl -w"
shbang="#!"$shbang

print "$shbang"                        >> $filename
print "#                 "             >> $filename
print "# Author:  $your_name"          >> $filename
print "# Date  :  $d        "          >> $filename
print "# Program Name: $filename "     >> $filename
print "# Objective:              "     >> $filename
print "#                         "     >> $filename
print " "                              >> $filename
chmod +x $filename
[ -n "$EDITOR" ] && $EDITOR $filename || vi $filename

